### ISSUE TITLE
Supplying argument does not remove prompt in `if-empty` mode

### ISSUE THREAD

**Issue by iamturns** [nanovazquez/yargs-interactive#13]
**Steps to replicate**

1. Create 'mixed mode' example as described within README.md
1. Invoke with `--name='Johh' --interactive` args (also shown in README)

**Expected behaviour**

I will *not* be prompted for `name`, as it has been supplied as an arg

**Actual behaviour**

I am prompted for `name`

**Potential fix**

I think I've fixed the problem locally with these changes:

```
--- a/node_modules/yargs-interactive/src/yargs-interactive.js
+++ b/node_modules/yargs-interactive/src/yargs-interactive.js
@@ -29,10 +29,15 @@ let yargsInteractive = (processArgs = process.argv.slice(2), cwd) => {
 
     // Remove options with prompt value set to 'never'
     // and options with prompt value set to 'if-empty' but no default value or value set via parameter
-    const interactiveOptions = filterObject(mergedOptions, (item, key) => (
-      item.prompt !== 'never'
-      && (item.prompt !== 'if-empty' || isEmpty(item.default) || isEmpty(argv[key]))
-    ));
+    const interactiveOptions = filterObject(mergedOptions, (item, key) => {
+      if (item.prompt === 'never') {
+        return false;
+      }
+      if (item.prompt === 'always') {
+        return true;
+      }
+      return isEmpty(item.default) && isEmpty(argv[key]);
+    });
 
     // Check if we should get the values from the interactive mode
     return argv.interactive

```

**Comment by nanovazquez** [comment]
Thanks @iamturns for reporting the issue! I'll take a look and see if I can make a quick PR with the fix. Stay tuned!

**Comment by nanovazquez** [comment]
Alright, version [2.0.2](https://github.com/nanovazquez/yargs-interactive/releases/tag/v2.0.2) fixes the issue. Could you please try again and reopen the issue if it's not fixed on your end? Thanks!

**Comment by iamturns** [comment]
Thanks @nanovazquez - super quick response, amazing job 👏
