### ISSUE TITLE
yargs fails when `choices` is set to a function

### ISSUE THREAD

**Issue by brandonweiss** [nanovazquez/yargs-interactive#22]
Inquirer allows the `choices` property to be an array or a function that returns an array (in order to make the choices dynamic based on previously answered questions). But it seems like yargs expects the `choices` property to be a [string or array](https://github.com/yargs/yargs/blob/7e1c8fc82083a9c9d4a7babdd8448bcd7ce122f6/yargs.js#L252)?

**Comment by nanovazquez** [comment]
Hey @brandonweiss. First of all, I'm really sorry for the late response, I didn't have the notifications turned on for this repo. It's fixed now.

You are right, given that this functionality is not provided by `yargs`, there is some work required to make it work in here. I haven't found any use case to support it, but in case you have one I'm open to receive a PR and review it. What do you think?

**Comment by brandonweiss** [comment]
No worries! I’ve certainly done that myself before 😓

Hmm… honestly it’s been so long I can’t remember what in particular I wanted this feature for 😅 Apparently it wasn’t a big enough problem because I completely forgot about it 🤷‍♂ Feel free to close!

**Comment by nanovazquez** [comment]
Will do, but feel free to open it again if you need it.

And sorry again for taking so long to answer.
